direction: right

chat: Web {
  icon: https://cdn.simpleicons.org/googlechrome
}

api: Hono API Server {
  grid-columns: 1
  grid-gap: 16
  style.font-size: 16
  style.bold: true

  hono-icon: "" {
    icon: https://cdn.simpleicons.org/hono
    shape: image
    width: 64
    height: 64
  }

  spacer: "" {
    width: 200
    height: 1
    style.opacity: 0
    style.stroke-width: 0
  }

  agent: LangGraph Agent {
    icon: https://cdn.simpleicons.org/langchain
  }
}

openai: OpenAI {
  icon: https://cdn.simpleicons.org/openai
  near: top-right
}

sandbox: Docker Sandbox {
  grid-columns: 1
  grid-gap: 16
  style.font-size: 16
  style.bold: true

  docker-icon: "" {
    icon: https://cdn.simpleicons.org/docker
    shape: image
    width: 64
    height: 64
  }

  spacer: "" {
    width: 200
    height: 1
    style.opacity: 0
    style.stroke-width: 0
  }

  cli: CLI {
    icon: https://cdn.simpleicons.org/gnubash
  }
}

keycloak: Keycloak {
  icon: https://cdn.simpleicons.org/letsencrypt
}

user: User {
  shape: person
}

chat <-> api: NDJSON
api.agent -> openai: inference {
  style.stroke-dash: 3
}
api.agent -> sandbox: exec commands

sandbox -> user: OAuth 2.0 device flow login URL {
  style.stroke-dash: 3
}
user -> keycloak: authenticates {
  style.stroke-dash: 3
}
