services:
  keycloak:
    build: .
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
      KC_LEGACY_OBSERVABILITY_INTERFACE: "true"
      KC_HTTP_MANAGEMENT_HEALTH_ENABLED: "false"
      KC_HTTP_ENABLED: "true"
      JAVA_OPTS_APPEND: -Djava.io.tmpdir=/dev/shm
    ports:
      - "8080:8080"
